- name: Verificar conectividad y puertos
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Verificar conectividad (ping) en los hosts del grupo linux
      ping:
      loop: "{{ groups['linux'] }}"

    - name: Verificar que el puerto 22 (SSH) esté abierto en los hosts del grupo linux
      wait_for:
        host: "{{ item }}"
        port: 22
        timeout: 5
        state: started
      loop: "{{ groups['linux'] }}"
      
    - name: Verificar conectividad (ping) en los hosts del grupo windows
      ping:
      loop: "{{ groups['windows'] }}"

    - name: Verificar que el puerto 3389 (RDP) esté abierto en los hosts del grupo windows
      wait_for:
        host: "{{ item }}"
        port: 3389
        timeout: 5
        state: started
      loop: "{{ groups['windows'] }}"


    
