- name: Verificar conectividad y puertos
  hosts: localhost
  gather_facts: false
  tasks:
    
    - name: Verificar que el puerto 22 (SSH) esté abierto
      wait_for:
        host: {{ item }}
        port: 22
        timeout: 5
        state: started
      loop: 
        - 10.172.52.185
        - 10.172.52.186
      
    - name: Verificar que el puerto 3389 (RDP) esté abierto
      wait_for:
        host: 10.172.52.187
        port: 3389
        timeout: 5
        state: started
    
